#!/usr/bin/env python3
"""Burst-validation for wiggle (time-varying filter).

Compares a Unity burst (`vipsim_assets/unity_refs/wiggle_burst/`) against a
matching Python burst generated by `apply_wiggle()` with the per-frame Timer
values recorded in Unity's metadata.json.

Usage:
    python scripts/validate_wiggle_burst.py \
        --unity-dir vipsim_assets/unity_refs/wiggle_burst \
        --baseline vipsim_assets/unity_refs/baseline.png \
        --out abs_diff_out/wiggle_burst

    # optional: also produce side-by-side MP4 (uses bundled ffmpeg)
    python scripts/validate_wiggle_burst.py --make-video
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_filter
from skimage.metrics import structural_similarity as _ssim

# Add repo root to sys.path so we can import vipsim_filters from anywhere.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from vipsim_filters import apply_wiggle  # noqa: E402


def ssim_blur(a: np.ndarray, b: np.ndarray, sigma: float = 4.0) -> float:
    a01 = a.astype(np.float32) / 255.0
    b01 = b.astype(np.float32) / 255.0
    af = gaussian_filter(a01, sigma=(sigma, sigma, 0))
    bf = gaussian_filter(b01, sigma=(sigma, sigma, 0))
    return float(_ssim(af, bf, channel_axis=2, data_range=1.0))


def make_side_by_side(unity: np.ndarray, python: np.ndarray) -> np.ndarray:
    return np.vstack([unity, python])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--unity-dir", type=Path,
                    default=Path("vipsim_assets/unity_refs/wiggle_burst"))
    ap.add_argument("--baseline", type=Path,
                    default=Path("vipsim_assets/unity_refs/baseline.png"))
    ap.add_argument("--out", type=Path,
                    default=Path("abs_diff_out/wiggle_burst"))
    ap.add_argument("--severity", type=float, default=1.0,
                    help="apply_wiggle severity (default 1.0). Unity capture uses raw amplitude, so 1.0 is correct.")
    ap.add_argument("--make-video", action="store_true")
    args = ap.parse_args()

    if not args.unity_dir.exists():
        sys.exit(f"Unity burst dir not found: {args.unity_dir}")
    if not args.baseline.exists():
        sys.exit(f"Baseline not found: {args.baseline}")

    meta_path = args.unity_dir / "metadata.json"
    if not meta_path.exists():
        sys.exit(f"metadata.json missing in {args.unity_dir}; re-run Unity burst capture.")
    meta = json.loads(meta_path.read_text())
    timers = meta["timers"]
    frame_times = meta["frame_times_s"]
    mode_int = int(meta.get("mode", 1))
    mode = "complex" if mode_int == 1 else "simple"
    freq = float(meta.get("frequency", 12.0))
    amp = float(meta.get("amplitude", 0.01))

    args.out.mkdir(parents=True, exist_ok=True)
    compare_dir = args.out / "compare"; compare_dir.mkdir(exist_ok=True)
    python_dir = args.out / "python";  python_dir.mkdir(exist_ok=True)

    baseline_img = Image.open(args.baseline).convert("RGB")
    baseline_np = np.asarray(baseline_img)
    print(f"Loaded baseline: {baseline_np.shape}, mode={mode}, freq={freq}, amp={amp}")

    scores = []
    for i, (t, timer) in enumerate(zip(frame_times, timers)):
        unity_path = args.unity_dir / f"frame_{i:03d}.png"
        if not unity_path.exists():
            print(f"  skip {i:03d}: {unity_path.name} missing")
            continue
        unity = np.asarray(Image.open(unity_path).convert("RGB"))

        py_img = apply_wiggle(baseline_img, severity=args.severity,
                              freq=freq, amplitude=amp,
                              timer=float(timer), mode=mode)
        python = np.asarray(py_img)

        Image.fromarray(python).save(python_dir / f"frame_{i:03d}.png")
        Image.fromarray(make_side_by_side(unity, python)).save(
            compare_dir / f"frame_{i:03d}.png")

        s = ssim_blur(unity, python)
        scores.append({"frame": i, "t": t, "timer": timer, "ssim_blur": s})
        print(f"  frame {i:03d} t={t:.2f}s timer={timer:.3f}  SSIM_blur={s:.3f}")

    summary = {
        "meta": meta,
        "scores": scores,
        "ssim_blur_mean": float(np.mean([s["ssim_blur"] for s in scores])) if scores else None,
        "ssim_blur_min": float(np.min([s["ssim_blur"] for s in scores])) if scores else None,
    }
    (args.out / "summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\nMean SSIM_blur: {summary['ssim_blur_mean']:.3f}  (min {summary['ssim_blur_min']:.3f})")
    print(f"Outputs: {args.out}")

    if args.make_video:
        ffmpeg = shutil.which("ffmpeg")
        if not ffmpeg:
            try:
                import imageio_ffmpeg
                ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
                print(f"Using bundled ffmpeg: {ffmpeg}")
            except Exception:
                print("ffmpeg not found and imageio-ffmpeg not installed; skipping --make-video")
                return
        mp4 = args.out / "compare.mp4"
        cmd = [ffmpeg, "-y", "-framerate", "2",
               "-i", str(compare_dir / "frame_%03d.png"),
               "-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2",
               "-c:v", "libx264", "-pix_fmt", "yuv420p", str(mp4)]
        print(f"Running: {' '.join(cmd)}")
        subprocess.run(cmd, check=False)
        print(f"Video: {mp4}")


if __name__ == "__main__":
    main()
