#!/usr/bin/env python3
"""Burst-validation for flickering_stars (time-varying filter).

Compares a Unity burst (`vipsim_assets/unity_refs/flickeringstars_burst/`)
against a matching Python burst generated by a time-aware reimplementation
of `FlickeringStars.cs`. Outputs per-frame side-by-side PNGs + a SSIM_blur
score table.

This script is intentionally STANDALONE — it does not import or modify
`vipsim_filters.py` or any other validation infrastructure. The time-aware
flicker function lives in this file. If it pans out, promote it later.

Usage:
    python scripts/validate_flickering_stars_burst.py \
        --unity-dir vipsim_assets/unity_refs/flickeringstars_burst \
        --baseline vipsim_assets/unity_refs/baseline.png \
        --out abs_diff_out/flickeringstars_burst

    # optional: also produce side-by-side MP4 (requires ffmpeg)
    python scripts/validate_flickering_stars_burst.py --make-video
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_filter
from skimage.metrics import structural_similarity as _ssim


# -----------------------------------------------------------------------------
# Time-aware flickering-stars (faithful port of FlickeringStars.cs Update loop)
# -----------------------------------------------------------------------------
# Unity logic in plain English:
#   - Start(): generate `n` stars. For each, pick (x, y) inside a disc of
#     `radius` around (0.5, 0.5). Pick `randomDelay ~ Uniform(0, 5)`. Set
#     fadeInStart = randomDelay, fadeOutEnd = randomDelay + fadeInDuration.
#   - Update(): elapsed += dt. If elapsed >= 5: regenerate, reset elapsed.
#   - Per-frame fade: in [0, fadeInDuration] window after fadeInStart →
#     ramp up; in [0, fadeOutDuration] window after fadeOutEnd → ramp down;
#     else 0.
#   - OnRenderImage: shader draws each star as a smooth disc of `starRadius`,
#     multiplied by fade, additively over the source image.
#
# We mirror this with a Python RNG. Bit-exactness with UnityEngine.Random is
# impossible (different PRNG); the goal is the same *temporal character*.

@dataclass
class StarSet:
    """One generation cycle's worth of stars (regenerated every 5 s in Unity)."""
    xs: np.ndarray         # UV coords in [0, 1], shape (n,)
    ys: np.ndarray
    fade_in_start: np.ndarray   # seconds, shape (n,)
    fade_out_end: np.ndarray


def _generate_starset(rng: np.random.Generator, n: int, radius: float,
                       fade_in_duration: float, t_now: float) -> StarSet:
    # Random.insideUnitCircle: rejection-sample inside unit disc, then scale.
    pts = []
    while len(pts) < n:
        cand = rng.uniform(-1.0, 1.0, size=(n * 2, 2))
        keep = cand[(cand[:, 0] ** 2 + cand[:, 1] ** 2) <= 1.0]
        pts.extend(keep[: n - len(pts)].tolist())
    arr = np.array(pts[:n])
    xs = 0.5 + arr[:, 0] * radius
    ys = 0.5 + arr[:, 1] * radius
    delays = rng.uniform(0.0, 5.0, size=n).astype(np.float32)
    fade_in_start = (t_now + delays).astype(np.float32)
    fade_out_end = (fade_in_start + fade_in_duration).astype(np.float32)
    return StarSet(xs.astype(np.float32), ys.astype(np.float32),
                   fade_in_start, fade_out_end)


def simulate_stars_at(t: float, *, n_stars: int, radius: float,
                       star_radius: float, fade_in_duration: float,
                       fade_out_duration: float, regen_period: float = 5.0,
                       seed: int = 42) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Replay Unity's Update loop deterministically up to time `t`.

    Returns (xs, ys, fades) in normalized UV + fade in [0, 1].
    """
    rng = np.random.default_rng(seed)
    # First generation at t=0 (Unity's Start()).
    sset = _generate_starset(rng, n_stars, radius, fade_in_duration, t_now=0.0)
    # Replay regens at t = regen_period, 2*regen_period, ... while < t.
    next_regen = regen_period
    while next_regen <= t:
        sset = _generate_starset(rng, n_stars, radius, fade_in_duration,
                                  t_now=next_regen)
        next_regen += regen_period

    # Per-star fade at time t (mirrors Unity Update body).
    time_since_fade_in_start = t - sset.fade_in_start
    time_since_fade_out_end = t - sset.fade_out_end
    fades = np.zeros(n_stars, dtype=np.float32)
    in_fade_in = (time_since_fade_in_start >= 0) & (time_since_fade_in_start < fade_in_duration)
    in_fade_out = (~in_fade_in) & (time_since_fade_out_end >= 0) & (time_since_fade_out_end < fade_out_duration)
    fades[in_fade_in] = np.clip(time_since_fade_in_start[in_fade_in] / max(fade_in_duration, 1e-6), 0.0, 1.0)
    fades[in_fade_out] = np.clip(1.0 - time_since_fade_out_end[in_fade_out] / max(fade_out_duration, 1e-6), 0.0, 1.0)
    return sset.xs, sset.ys, fades


def render_stars(baseline: np.ndarray, xs: np.ndarray, ys: np.ndarray,
                   fades: np.ndarray, star_radius_uv: float) -> np.ndarray:
    """Draw stars onto a copy of baseline. `xs/ys` in UV; `star_radius_uv` in UV.

    Matches the shader: `inside = smoothstep(starRadius, 0, distance(uv, coord))`,
    then color = lerp(source, white, inside * fade).
    """
    h, w = baseline.shape[:2]
    out = baseline.astype(np.float32).copy()
    sr_px = max(1.0, star_radius_uv * min(h, w))  # use min dim to keep circles round
    # Aspect: distance in UV is anisotropic if we don't correct. Match Unity:
    # the shader computes distance(uv, coord) in normalised UV space which is
    # naturally stretched. We do the same in pixel space using w & h separately
    # but normalising by the smaller dim → near-circular at 2:1.
    radius_px = star_radius_uv * h  # height-based, matches shader's UV
    # Pre-build a small disc kernel
    kr = int(np.ceil(radius_px * 1.5)) + 1
    y_grid, x_grid = np.mgrid[-kr:kr + 1, -kr:kr + 1]
    dist = np.sqrt(x_grid * x_grid + y_grid * y_grid)
    disc = np.clip(1.0 - dist / max(radius_px, 1e-6), 0.0, 1.0)
    # Smoothstep edge for soft star (matches shader smoothstep)
    disc = disc * disc * (3.0 - 2.0 * disc)

    for x, y, fade in zip(xs, ys, fades):
        if fade <= 0.0:
            continue
        cx = int(round(x * (w - 1)))
        cy = int(round((1.0 - y) * (h - 1)))  # Unity UV y-up
        y0, y1 = max(0, cy - kr), min(h, cy + kr + 1)
        x0, x1 = max(0, cx - kr), min(w, cx + kr + 1)
        ky0 = y0 - (cy - kr); ky1 = ky0 + (y1 - y0)
        kx0 = x0 - (cx - kr); kx1 = kx0 + (x1 - x0)
        mask = (disc[ky0:ky1, kx0:kx1] * fade)[..., None]
        out[y0:y1, x0:x1] = out[y0:y1, x0:x1] * (1.0 - mask) + 255.0 * mask
    return np.clip(out, 0, 255).astype(np.uint8)


# -----------------------------------------------------------------------------
# Comparison + reporting
# -----------------------------------------------------------------------------

def ssim_blur(a: np.ndarray, b: np.ndarray, sigma: float = 4.0) -> float:
    a01 = a.astype(np.float32) / 255.0
    b01 = b.astype(np.float32) / 255.0
    af = gaussian_filter(a01, sigma=(sigma, sigma, 0))
    bf = gaussian_filter(b01, sigma=(sigma, sigma, 0))
    return float(_ssim(af, bf, channel_axis=2, data_range=1.0))


def make_side_by_side(unity: np.ndarray, python: np.ndarray) -> np.ndarray:
    """Stack Unity (top) above Python (bottom) for visual comparison."""
    return np.vstack([unity, python])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--unity-dir", type=Path,
                    default=Path("vipsim_assets/unity_refs/flickeringstars_burst"))
    ap.add_argument("--baseline", type=Path,
                    default=Path("vipsim_assets/unity_refs/baseline.png"))
    ap.add_argument("--out", type=Path,
                    default=Path("abs_diff_out/flickeringstars_burst"))
    ap.add_argument("--seed", type=int, default=42,
                    help="Python RNG seed (matches Unity's Random.InitState)")
    ap.add_argument("--make-video", action="store_true",
                    help="Stitch comparison frames into an MP4 via ffmpeg")
    args = ap.parse_args()

    if not args.unity_dir.exists():
        sys.exit(f"Unity burst dir not found: {args.unity_dir}")
    if not args.baseline.exists():
        sys.exit(f"Baseline not found: {args.baseline}")

    meta_path = args.unity_dir / "metadata.json"
    if not meta_path.exists():
        sys.exit(f"metadata.json missing in {args.unity_dir} — re-run Unity burst capture.")
    meta = json.loads(meta_path.read_text())
    frame_times = meta["frame_times_s"]
    n_stars = int(meta["num_stars"])
    radius = float(meta["radius"])
    star_radius = float(meta["star_radius"])
    fade_in = float(meta["fade_in_duration"])
    fade_out = float(meta["fade_out_duration"])

    args.out.mkdir(parents=True, exist_ok=True)
    compare_dir = args.out / "compare"; compare_dir.mkdir(exist_ok=True)
    python_dir = args.out / "python";  python_dir.mkdir(exist_ok=True)

    baseline = np.asarray(Image.open(args.baseline).convert("RGB"))
    print(f"Loaded baseline: {baseline.shape}")

    scores = []
    for i, t in enumerate(frame_times):
        unity_path = args.unity_dir / f"frame_{i:03d}.png"
        if not unity_path.exists():
            print(f"  skip {i:03d}: {unity_path.name} missing")
            continue
        unity = np.asarray(Image.open(unity_path).convert("RGB"))

        xs, ys, fades = simulate_stars_at(
            t, n_stars=n_stars, radius=radius, star_radius=star_radius,
            fade_in_duration=fade_in, fade_out_duration=fade_out,
            seed=args.seed,
        )
        python = render_stars(baseline, xs, ys, fades, star_radius)

        Image.fromarray(python).save(python_dir / f"frame_{i:03d}.png")
        Image.fromarray(make_side_by_side(unity, python)).save(
            compare_dir / f"frame_{i:03d}.png")

        s = ssim_blur(unity, python)
        n_visible = int(np.sum(fades > 0.01))
        scores.append({"frame": i, "t": t, "ssim_blur": s, "n_visible": n_visible})
        print(f"  frame {i:03d} t={t:.2f}s  SSIM_blur={s:.3f}  visible_stars={n_visible}")

    summary = {
        "meta": meta,
        "scores": scores,
        "ssim_blur_mean": float(np.mean([s["ssim_blur"] for s in scores])) if scores else None,
        "ssim_blur_min":  float(np.min([s["ssim_blur"] for s in scores])) if scores else None,
    }
    (args.out / "summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\nMean SSIM_blur: {summary['ssim_blur_mean']:.3f}  (min {summary['ssim_blur_min']:.3f})")
    print(f"Outputs: {args.out}")

    if args.make_video:
        ffmpeg = shutil.which("ffmpeg")
        if not ffmpeg:
            try:
                import imageio_ffmpeg
                ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
                print(f"Using bundled ffmpeg: {ffmpeg}")
            except Exception:
                print("ffmpeg not found and imageio-ffmpeg not installed; skipping --make-video")
                return
        mp4 = args.out / "compare.mp4"
        cmd = [ffmpeg, "-y", "-framerate", "2",
               "-i", str(compare_dir / "frame_%03d.png"),
               "-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2",
               "-c:v", "libx264", "-pix_fmt", "yuv420p", str(mp4)]
        print(f"Running: {' '.join(cmd)}")
        subprocess.run(cmd, check=False)
        print(f"Video: {mp4}")


if __name__ == "__main__":
    main()
